<a href="https://colab.research.google.com/github/imhilla/allmlnotebooks/blob/main/buildingblocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# the mathematical building blocks of neural networks

In [ ]:
# a category in a classification problem is called class
# data points are called samples
# the class associated with a specific sample is called label


In [2]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [11]:
# an optimizer - mechanism through which the model will update itself based on the training data it sees, so as to improve it's performance
# a loss function - how the model will be able to measure it's performance on the training data and thus how it will be able to steer itself in the right direction
# metrics to monitor during training and testing

model.compile(
    optimizer='rmsprop',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [12]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [14]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 13ms/step - loss: 0.2620 - accuracy: 0.9242
Epoch 2/5
469/469 [==============================] - 5s 11ms/step - loss: 0.1061 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 6s 13ms/step - loss: 0.0707 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0507 - accuracy: 0.9851
Epoch 5/5
469/469 [==============================] - 6s 13ms/step - loss: 0.0373 - accuracy: 0.9892


In [18]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 40ms/step


array([1.6222158e-07, 1.0364596e-08, 1.4409175e-05, 5.2401668e-04,
       4.1448556e-11, 7.5076559e-07, 5.3401793e-11, 9.9944937e-01,
       4.5840475e-06, 6.8108470e-06], dtype=float32)

In [19]:
predictions[0].argmax()

7

In [20]:
predictions[0][7]

0.9994494

In [21]:
test_labels[0]

7

In [22]:
# evaluating the model on new data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 4ms/step - loss: 0.0654 - accuracy: 0.9796
test_acc: 0.9796000123023987


In [ ]:
# 2.2 Data representations for neural networks
